export enum NAVIGATION_KEYS {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	VERIFY_CODE = 'VERIFY-CODE',
	SUCCESS_VERIFICATION = 'SUCCESS-VERIFICATION',
	PRODUCTS = 'PRODUCTS',
	PRODUCT_INFO = 'PRODUCT-INFO',
	ORDERS = 'ORDERS',
	SETTINGS = 'SETTINGS',
	FORGOT_PASSWORD = 'FORGOT-PASSWORD',
	RECOVER_PASSWORD = 'RECOVER-PASSWORD',
	PROFILE = 'PROFILE',
	RESET_PASSWORD = 'RESET-PASSWORD',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.VERIFY_CODE]: { email: string };
	[NAVIGATION_KEYS.SUCCESS_VERIFICATION]: undefined;
	[NAVIGATION_KEYS.PRODUCTS]: undefined;
	[NAVIGATION_KEYS.PRODUCT_INFO]: { productId: string };
	[NAVIGATION_KEYS.ORDERS]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
	[NAVIGATION_KEYS.FORGOT_PASSWORD]: undefined;
	[NAVIGATION_KEYS.RECOVER_PASSWORD]: { token: string };
	[NAVIGATION_KEYS.PROFILE]: undefined;
	[NAVIGATION_KEYS.RESET_PASSWORD]: undefined;
};
