export enum NAVIGATION_KEYS {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	VERIFY_CODE = 'VERIFY-CODE',
	SUCCESS_VERIFICATION = 'SUCCESS_VERIFICATION',
	PRODUCTS = 'PRODUCTS',
	PRODUCT_INFO = 'PRODUCT-INFO',
	ORDERS = 'ORDERS',
	SETTINGS = 'SETTINGS',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.VERIFY_CODE]: { email: string };
	[NAVIGATION_KEYS.SUCCESS_VERIFICATION]: undefined;
	[NAVIGATION_KEYS.PRODUCTS]: undefined;
	[NAVIGATION_KEYS.PRODUCT_INFO]: { productId: string };
	[NAVIGATION_KEYS.ORDERS]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
};
